package ru.romanow.camunda.domain.enums

enum class Status {
    CALCULATION_STARTED,

    DATA_PREPARED,
    DATA_COPIED_TO_STAGED,

    ETL_START,
    ETL_COMPLETED,

    CALCULATION_START,
    CALCULATION_COMPLETED,

    REVERSED_ETL_START,
    REVERSED_ETL_COMPLETED,

    DATA_COPIED_FROM_STAGED,

    CALCULATION_FINISHED,
}