spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cashflow
    username: program
    password: test
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 40
      minimum-idle: 40

services:
  macro-scenario-url: http://wiremock:8080
  transfer-rate-url: http://wiremock:8080
  product-scenario-url: http://wiremock:8080
  drp-command-url: http://wiremock:8080
  balance-result-url: http://wiremock:8080