spring:
  datasource:
    password: test
    driver-class-name: org.postgresql.Driver
    username: program
    url: jdbc:postgresql://localhost:5432/cashflow
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false

services:
  macro-scenario-url: http://localhost:9999
  transfer-rate-url: http://localhost:9999
  product-scenario-url: http://localhost:9999
  drp-command-url: http://localhost:9999