spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cashflow
    password: test
    username: program
    driver-class-name: org.postgresql.Driver

services:
  macro-scenario-url: http://wiremock:9999
  transfer-rate-url: http://wiremock:9999
  product-scenario-url: http://wiremock:9999
  drp-command-url: http://wiremock:9999
  balance-result-url: http://wiremock:9999