server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: cashflow
  main.banner-mode: off

management:
  endpoint:
    health.probes.enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure.include: info,health,loggers
  health.diskspace.enabled: false
  endpoint.health.show-details: always
  info.git.mode: simple
  health:
    readinessstate.enabled: true
    livenessstate.enabled: true

springdoc:
  api-docs.path: /api-docs
  paths-to-match: /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All tasks

services:
  macro-scenario-url: ${MACRO_SCENARIO_URL:}
  transfer-rate-url: ${TRANSFER_RATE_URL:}
  product-scenario-url: ${PRODUCT_SCENARIO_URL:}
  drp-command-url: ${DRP_COMMAND_URL:}
